[build]
target = "index.html"
dist = "dist"
release = false
public_url = "/"
# public_url = "/{project_name}/"            # for {username}.github.io/{project_name}
# public_url = "/"                           # for {username}.github.io

[watch]
watch = [
    "./index.html",
    "src/",
    "css/",
    "static/",
]

[clean]
dist = "dist"

[[hooks]]
stage = "pre_build"
command = "sh"
# run tailwind build with webpack
command_arguments = [
    "-c",
    "npm install webpack-cli && npm run build_css",
]
# https://github.com/thedodd/trunk/issues/89 so install master branch for trunk
# rustup target add wasm32-unknown-unknown # needed if not already setup

# COMMANDS FOR BUILD:
# trunk serve --public-url=/dev/